### ISSUE TITLE
use with springboot 4

### ISSUE THREAD

**Issue by franalta** [mpuening/learn-webservices-jaxrpc#1]
Hi, first of all thank You to have shared a project template for the old standard xmlrpc. Even if is no more used, there is always the change to encounter this old standard. After this, I have cloned your project and I have read the source code, it's possible use spring boot 4 instead of Spring boot 3?
Waiting for an answer

Best regards

**Comment by mpuening** [comment]
What do you mean by Spring Boot 4? As I write this, the latest version of Spring Boot is 3.1.4. Is this the version that you mean?

(update) After more thought, perhaps you are referring to Spring Web Services which is version 4.

**Comment by franalta** [comment]
Hi, thank You for the answer. You have right, I have confused spring framework version wth spring boot version library... I have another thing to ask You: if I want made server jar (always standalone) instead war how should I do? I know that war was java to load on application server while jar was library or application standalone (without application server). Now I see that You have used war, why? It's possible make a jar application spring boot?

**Comment by mpuening** [comment]
There was a time when Spring Web Services supported RPC. But it has long been deprecated, and then finally removed when Spring switched to the jakarta namespace. Because of this and also having nice experience with the AxisServlet, I avoided Spring Web Services and used AxisServlet directly.

As for the jar/war issue, yes, learn-webservices-jaxrpc-server/pom.xml has the wrong packaging. It should be "jar" because I intend people to run the server as a standalone Spring Boot jar file. I will change this.

**Comment by franalta** [comment]
Hi, I have tried to set war packaging in pom.xml of server project but I'll get the following error:
2023-10-20 17:56:28,523 - ERROR o.a.a.c.EngineConfigurationFactoryServlet[EngineConfigurationFactoryServlet.java:162] - Unable to find config file.  Creating new servlet engine config file: /WEB-INF/server-config.wsdd
2023-10-20 17:56:28,563 - ERROR o.a.a.c.EngineConfigurationFactoryServlet[EngineConfigurationFactoryServlet.java:176] - Problem with servlet engine /WEB-INF directory

2023-10-20 17:56:28,565 - WARN  o.a.a.c.EngineConfigurationFactoryServlet[EngineConfigurationFactoryServlet.java:184] - Unable to load/create servlet engine config file, attempting internal default (from jar).
2023-10-20 17:56:28,642 - WARN  o.apache.axis.utils.JavaUtils[JavaUtils.java:1308] - Unable to find required classes (javax.activation.DataHandler and javax.mail.internet.MimeMultipart). Attachment support is disabled.

and inside the response I'll get a 500 error response with following body

> <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
>    <soapenv:Body>
>       <soapenv:Fault>
>          <faultcode xmlns:ns1="http://xml.apache.org/axis/">ns1:Server.NoService</faultcode>
>          <faultstring>The AXIS engine could not find a target service to invoke!  targetService is WEBPanelServices</faultstring>
>          <detail>
>             <ns2:hostname xmlns:ns2="http://xml.apache.org/axis/">PC01A</ns2:hostname>
>          </detail>
>       </soapenv:Fault>
>    </soapenv:Body>
> </soapenv:Envelope>

there's a way to fix this issue? Obviously compiling with war package all works fine.

P.S.: adding this plugin section inside pom.xml file
      

> <plugin>
>        	<artifactId>maven-dependency-plugin</artifactId>
>              	
>              	<version>3.6.0</version>
>              	<executions>
>            			<execution>
>              			<id>analyze</id>
>              			<phase>package</phase>
>              			<goals>
>                				<goal>analyze</goal>
>              			</goals>
>            			</execution>
>          	</executions>
> </plugin>

after compiling the entire pom parent project I'll get the following lines:

[[1;34mINFO[m] [1m--- [0;32mmaven-dependency-plugin:3.6.0:analyze[m [1m(analyze)[m @ [36mlearn-webservices-jaxrpc-server[0;1m ---[m
[[1;33mWARNING[m] Unused declared dependencies found:
[[1;33mWARNING[m]    org.springframework.boot:spring-boot-starter-web:jar:2.7.16:compile
[[1;33mWARNING[m]    org.springframework.boot:spring-boot-starter-security:jar:2.7.16:compile

Are the 2 dependency necessary or plugin analysis work is wrong?

Thank You

Cheers

**Comment by mpuening** [comment]
I now understand why the server was a war file... I placed the server-config.wsdd file in the WEB-INF directory. When one changes the packaging to a jar file, the src/main/webapp directory is ignored and server-config.wsdd is not included in the resulting jar file. This results in the error shown above. To resolve the issue, one just needs to move the file to the src/main/resources directory (to be included on the class-path).

I made the changes on the following branch:

https://github.com/mpuening/learn-webservices-jaxrpc/tree/feature/jarexe

Let me know if the changes on the branch resolve the issues and I'll merge them to the main branch.

**Comment by franalta** [comment]
hi, I have tried to move server-config.wsdd in src/main/resources and in the pom child of server module I have set <packaging>jar<\packaging> element (instead your branch doesn't have it) but now I'll get the following error:
`2023-10-24 21:36:24,418 - ERROR o.a.a.c.EngineConfigurationFactoryServlet[EngineConfigurationFactoryServlet.java:162] - Unable to find config file.  Creating new servlet engine config file: /WEB-INF/server-config.wsdd
2023-10-24 21:36:24,505 - ERROR o.a.a.c.EngineConfigurationFactoryServlet[EngineConfigurationFactoryServlet.java:176] - Problem with servlet engine /WEB-INF directory
org.apache.axis.ConfigurationException: Configuration file directory 'C:\Users\xxx\AppData\Local\Temp\tomcat-docbase.10443.4917710451593158279\WEB-INF' does not exist or is not a directory or is not readable.
        at org.apache.axis.configuration.FileProvider.<init>(FileProvider.java:99)
.
.
.
2023-10-24 21:36:24,507 - WARN  o.a.a.c.EngineConfigurationFactoryServlet[EngineConfigurationFactoryServlet.java:184] - Unable to load/create servlet engine config file, attempting internal default (from jar).
2023-10-24 21:36:24,589 - WARN  o.apache.axis.utils.JavaUtils[JavaUtils.java:1308] - Unable to find required classes (javax.activation.DataHandler and javax.mail.internet.MimeMultipart). Attachment support is disabled.`

Should I remove above element <packaging>jar<\packaging> in the pom.xml child ?

p.s.: I have found this article on stackoverflow https://stackoverflow.com/questions/53123351/how-can-i-create-executable-jars-with-embedded-tomcat-9 , can be it is useful to fix the issue?

**Comment by mpuening** [comment]
The stack trace you have shown is expected behavior of Axis when it cannot find the server config file in the WEB-INF directory. But if you continue reading the messages, you'll see that it proceeds to the fallback location (the class-path). The application, as is, should work for you despite the error messages. If you prefer to not see the error messages, just disable the logger like I have done in the latest commit to the branch I mentioned in my previous comment.

**Comment by franalta** [comment]
ok, it's work now (I haven't seen your line added in the application.yml because I'm developing a new project), but however was interesting also go into detail in stackoverflow link above solutions (so we can still have enabled axis log) or also if it's possible update plugin tomcat7:exec-war to tomcat9 (plugin is explained here https://stackoverflow.com/questions/31959455/deploy-a-web-application-with-tomcat-included-in-one-jar ). I think that exec-war plugin it's a more secure solution, because if occurs special circumstances at run-time (or changes during develop) tomcat can break (or some thing will be more difficult to do). However thank You for the help.
